INSERT INTO application.accounts(created_at, updated_at, title, sum, user_id, bank_id)
VALUES (now(), now(), 'Личный счет', 0, 1, 1);
INSERT INTO application.accounts(created_at, updated_at, title, sum, user_id, bank_id)
VALUES (now(), now(), 'Личный счет1', 0, 1, 2);
INSERT INTO application.accounts(created_at, updated_at, title, sum, user_id, bank_id)
VALUES (now(), now(), 'Личный счет2', 0, 1, 3);
INSERT INTO application.accounts(created_at, updated_at, title, sum, user_id, bank_id)
VALUES (now(), now(), 'Личный счет3', 0, 1, 4);
INSERT INTO application.accounts(created_at, updated_at, title, sum, user_id, bank_id)
VALUES (now(), now(), 'Личный счет', 0, 2, 1);
INSERT INTO application.accounts(created_at, updated_at, title, sum, user_id, bank_id)
VALUES (now(), now(), 'Личный счет1', 0, 2, 2);
INSERT INTO application.accounts(created_at, updated_at, title, sum, user_id, bank_id)
VALUES (now(), now(), 'Личный счет2', 0, 2, 3);
INSERT INTO application.accounts(created_at, updated_at, title, sum, user_id, bank_id)
VALUES (now(), now(), 'Личный счет3', 0, 2, 4);
INSERT INTO application.accounts(created_at, updated_at, title, sum, user_id, bank_id)
VALUES (now(), now(), 'Личный счет', 0, 3, 1);
INSERT INTO application.accounts(created_at, updated_at, title, sum, user_id, bank_id)
VALUES (now(), now(), 'Личный счет1', 0, 3, 2);
INSERT INTO application.accounts(created_at, updated_at, title, sum, user_id, bank_id)
VALUES (now(), now(), 'Личный счет2', 0, 3, 3);
INSERT INTO application.accounts(created_at, updated_at, title, sum, user_id, bank_id)
VALUES (now(), now(), 'Личный счет3', 0, 3, 4);
INSERT INTO application.accounts(created_at, updated_at, title, sum, user_id, bank_id)
VALUES (now(), now(), 'Личный счет', 0, 4, 1);
INSERT INTO application.accounts(created_at, updated_at, title, sum, user_id, bank_id)
VALUES (now(), now(), 'Личный счет1', 0, 4, 2);
INSERT INTO application.accounts(created_at, updated_at, title, sum, user_id, bank_id)
VALUES (now(), now(), 'Личный счет2', 0, 4, 3);
INSERT INTO application.accounts(created_at, updated_at, title, sum, user_id, bank_id)
VALUES (now(), now(), 'Личный счет3', 0, 4, 4);
INSERT INTO application.accounts(created_at, updated_at, title, sum, user_id, bank_id)
VALUES (now(), now(), 'Личный счет', 0, 5, 1);
INSERT INTO application.accounts(created_at, updated_at, title, sum, user_id, bank_id)
VALUES (now(), now(), 'Личный счет1', 0, 5, 2);
INSERT INTO application.accounts(created_at, updated_at, title, sum, user_id, bank_id)
VALUES (now(), now(), 'Личный счет2', 0, 5, 3);
INSERT INTO application.accounts(created_at, updated_at, title, sum, user_id, bank_id)
VALUES (now(), now(), 'Личный счет3', 0, 5, 4);
INSERT INTO application.accounts(created_at, updated_at, title, sum, user_id, bank_id)
VALUES (now(), now(), 'Личный счет', 0, 6, 1);
INSERT INTO application.accounts(created_at, updated_at, title, sum, user_id, bank_id)
VALUES (now(), now(), 'Личный счет1', 0, 6, 2);
INSERT INTO application.accounts(created_at, updated_at, title, sum, user_id, bank_id)
VALUES (now(), now(), 'Личный счет2', 0, 6, 3);
INSERT INTO application.accounts(created_at, updated_at, title, sum, user_id, bank_id)
VALUES (now(), now(), 'Личный счет3', 0, 6, 4);
INSERT INTO application.accounts(created_at, updated_at, title, sum, user_id, bank_id)
VALUES (now(), now(), 'Личный счет', 0, 7, 1);
INSERT INTO application.accounts(created_at, updated_at, title, sum, user_id, bank_id)
VALUES (now(), now(), 'Личный счет1', 0, 7, 2);
INSERT INTO application.accounts(created_at, updated_at, title, sum, user_id, bank_id)
VALUES (now(), now(), 'Личный счет2', 0, 7, 3);
INSERT INTO application.accounts(created_at, updated_at, title, sum, user_id, bank_id)
VALUES (now(), now(), 'Личный счет3', 0, 7, 4);
INSERT INTO application.accounts(created_at, updated_at, title, sum, user_id, bank_id)
VALUES (now(), now(), 'Личный счет', 0, 9, 1);
INSERT INTO application.accounts(created_at, updated_at, title, sum, user_id, bank_id)
VALUES (now(), now(), 'Личный счет1', 0, 9, 2);
INSERT INTO application.accounts(created_at, updated_at, title, sum, user_id, bank_id)
VALUES (now(), now(), 'Личный счет2', 0, 9, 3);
INSERT INTO application.accounts(created_at, updated_at, title, sum, user_id, bank_id)
VALUES (now(), now(), 'Личный счет3', 0, 9, 4);
INSERT INTO application.accounts(created_at, updated_at, title, sum, user_id, bank_id)
VALUES (now(), now(), 'Личный счет', 0, 10, 1);
INSERT INTO application.accounts(created_at, updated_at, title, sum, user_id, bank_id)
VALUES (now(), now(), 'Личный счет1', 0, 10, 2);
INSERT INTO application.accounts(created_at, updated_at, title, sum, user_id, bank_id)
VALUES (now(), now(), 'Личный счет2', 0, 10, 3);
INSERT INTO application.accounts(created_at, updated_at, title, sum, user_id, bank_id)
VALUES (now(), now(), 'Личный счет3', 0, 10, 4);
INSERT INTO application.accounts(created_at, updated_at, title, sum, user_id, bank_id)
VALUES (now(), now(), 'Личный счет', 0, 11, 1);
INSERT INTO application.accounts(created_at, updated_at, title, sum, user_id, bank_id)
VALUES (now(), now(), 'Личный счет1', 0, 11, 2);
INSERT INTO application.accounts(created_at, updated_at, title, sum, user_id, bank_id)
VALUES (now(), now(), 'Личный счет2', 0, 11, 3);
INSERT INTO application.accounts(created_at, updated_at, title, sum, user_id, bank_id)
VALUES (now(), now(), 'Личный счет3', 0, 11, 4);